#!/usr/bin/env python
"""Migrate the preflight-02 TRAINING responses/scores from `public` into schema `app`.

DRY RUN BY DEFAULT per CORE.md §4. Idempotent. `--undo` removes exactly what it created.

WHAT THIS IS, AND WHAT IT IS NOT
    These 64 rows were generated by scripts/training/seed_training_preflight02.py. They are
    not real student work, and migrate_public_to_app.py deliberately left them behind for
    that reason. They are being brought across now for one purpose: the Grade view has no
    submissions to render, so nobody can see whether it works before the term starts.

    >>> THIS IS TEST DATA IN A PRODUCTION SCHEMA. Run --undo before real students submit,
    >>> or the cohort's first week is polluted with 64 fabricated submissions.

WHY TWO CONNECTIONS
    The app tier holds no rights on `public` (bootstrap §8 keeps that window closed), and
    `claude_code_recker` holds none on `app`. Rather than open the migration window — a
    postgres-level grant, and one more thing to remember to close — this reads with the
    legacy credential and writes with the app one. Nothing can write to `public` at any
    point: the read connection is only ever used for SELECT.

THE MAPPING
    public.responses            ->  app.submissions + app.submission_activities
      answers                        submission_activities.content (on the WRITTEN activity)
      submitted_at                   submissions.committed_at, status='committed'
    public.scores               ->  app.grades
      question_scores                grades.question_scores  (shape unchanged)
      total_score / max_total        points_earned / points_possible
      q2_effort, q3_understanding    grades.diagnostic  (never affects points — CORE.md §6)
      is_finalized (all false)       is_finalized=false, source='ai_suggested'

    The student is reached through their ENROLMENT, which is what every per-student table in
    `app` keys on. A response whose student is not enrolled in the target offering is skipped
    and reported rather than guessed at.

Usage (from the repo root, via the project venv):
  .venv/Scripts/python scripts/app_migration/migrate_training_responses.py
  .venv/Scripts/python scripts/app_migration/migrate_training_responses.py --commit
  .venv/Scripts/python scripts/app_migration/migrate_training_responses.py --undo --commit
"""
import argparse
import json
import sys
from pathlib import Path

import psycopg2
import psycopg2.extras

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "supabase" / "admin"))
from app_tier_check import load, connect  # noqa: E402

COURSE = "phys-215"
TERM = "fall-2026"
SLUG = "preflight-02"
LEGACY_ASSIGNMENT = "preflight-02"      # id in public.assignments


def read_public():
    """Read-only connection to `public` via the legacy operator credential."""
    cfg_path = ROOT / "supabase" / "admin" / "config.json"
    if not cfg_path.is_file():
        sys.exit(f"Need {cfg_path} to read `public` (see supabase/admin/README.md).")
    cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
    conn = psycopg2.connect(
        host=cfg["host"], port=cfg["port"], dbname=cfg["dbname"], user=cfg["user"],
        password=cfg["password"], sslmode=cfg.get("sslmode", "require"), connect_timeout=20)
    conn.set_session(readonly=True)      # belt and braces: this connection cannot write
    return conn


def write_app():
    cfg, tiers = load()
    tier = tiers.get("dml") or tiers.get("owner")
    if not tier:
        sys.exit("Need PREP_APP_DML_ROLE (or owner) in supabase/admin/.env.")
    conn = connect(cfg, tier)
    conn.autocommit = False
    return conn


def resolve_target(cur):
    """The offering, its written activity, and enrolment ids by student, in `app`."""
    cur.execute("""
        SELECT ao.id, ao.points_possible, ao.grading_mode
          FROM app.assignment_offerings ao
          JOIN app.assignments a       ON a.id  = ao.assignment_id
          JOIN app.course_offerings co ON co.id = ao.course_offering_id
          JOIN app.courses c           ON c.id  = co.course_id
          JOIN app.terms t             ON t.id  = co.term_id
         WHERE c.code=%s AND t.code=%s AND a.slug=%s""", (COURSE, TERM, SLUG))
    row = cur.fetchone()
    if not row:
        sys.exit(f"No assignment offering for {COURSE}/{TERM}/{SLUG} in `app`.")
    offering_id, points_possible, grading_mode = row

    cur.execute("""
        SELECT act.id FROM app.activities act
          JOIN app.offering_activities oa ON oa.activity_id = act.id
         WHERE oa.assignment_offering_id=%s AND act.modality='written'""", (offering_id,))
    act = cur.fetchone()
    if not act:
        sys.exit("That offering has no written activity to attach answers to.")

    cur.execute("""
        SELECT e.student_id, e.id FROM app.enrollments e
          JOIN app.sections s ON s.id = e.section_id
         WHERE s.course_offering_id = (SELECT course_offering_id
                                         FROM app.assignment_offerings WHERE id=%s)""",
                (offering_id,))
    return offering_id, act[0], float(points_possible), grading_mode, dict(cur.fetchall())


def undo(cur, offering_id, commit):
    print(f"{'COMMITTING' if commit else 'DRY RUN — will roll back'}: removing training data\n")
    for label, sql in [
        ("submission_activities", """DELETE FROM app.submission_activities
             WHERE submission_id IN (SELECT id FROM app.submissions
                                      WHERE assignment_offering_id=%s)"""),
        ("grades",      "DELETE FROM app.grades      WHERE assignment_offering_id=%s"),
        ("submissions", "DELETE FROM app.submissions WHERE assignment_offering_id=%s"),
    ]:
        cur.execute(sql, (offering_id,))
        print(f"  {cur.rowcount:>4}  {label}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--commit", action="store_true", help="actually write; otherwise roll back")
    ap.add_argument("--undo", action="store_true", help="remove what this script created")
    args = ap.parse_args()

    app_conn = write_app()
    cur = app_conn.cursor()
    cur.execute("SET search_path = app, public")

    offering_id, activity_id, points_possible, grading_mode, enrolment_of = resolve_target(cur)
    print(f"target offering : {offering_id}  ({COURSE} {TERM} {SLUG})")
    print(f"written activity: {activity_id}")
    print(f"points_possible : {points_possible}  (grading_mode={grading_mode})")
    print(f"enrolments      : {len(enrolment_of)}\n")

    if args.undo:
        undo(cur, offering_id, args.commit)
        app_conn.commit() if args.commit else app_conn.rollback()
        print("\n" + ("REMOVED." if args.commit else "Rolled back — dry run."))
        cur.close(); app_conn.close()
        return

    pub = read_public()
    pcur = pub.cursor(cursor_factory=psycopg2.extras.DictCursor)
    pcur.execute("""SELECT student_id, answers, submitted_at, updated_at
                      FROM public.responses WHERE assignment_id=%s""", (LEGACY_ASSIGNMENT,))
    responses = pcur.fetchall()
    pcur.execute("""SELECT student_id, question_scores, total_score, max_total,
                           q2_effort, q3_understanding
                      FROM public.scores WHERE assignment_id=%s""", (LEGACY_ASSIGNMENT,))
    scores = {r["student_id"]: r for r in pcur.fetchall()}
    pub.close()

    print(f"{'COMMITTING' if args.commit else 'DRY RUN — nothing will be written'}\n")
    print(f"read from public: {len(responses)} responses, {len(scores)} scores\n")

    n_sub = n_act = n_grade = 0
    skipped = []
    for r in responses:
        enr = enrolment_of.get(r["student_id"])
        if not enr:
            skipped.append(r["student_id"])
            continue

        committed = r["submitted_at"] or r["updated_at"]
        cur.execute("""
            INSERT INTO app.submissions (enrollment_id, assignment_offering_id,
                                         chosen_activity_id, status, committed_at)
            VALUES (%s,%s,%s,'committed',%s)
            ON CONFLICT (enrollment_id, assignment_offering_id) DO UPDATE
              SET chosen_activity_id = EXCLUDED.chosen_activity_id
            RETURNING id""", (enr, offering_id, activity_id, committed))
        sub_id = cur.fetchone()[0]
        n_sub += 1

        cur.execute("""
            INSERT INTO app.submission_activities (submission_id, activity_id, content, is_final)
            VALUES (%s,%s,%s,true)
            ON CONFLICT (submission_id, activity_id) DO UPDATE
              SET content = EXCLUDED.content, is_final = true""",
            (sub_id, activity_id, json.dumps(r["answers"] or {})))
        n_act += 1

        s = scores.get(r["student_id"])
        if not s:
            continue
        # The CHECK bounds points_earned by points_possible, and the offering is authoritative
        # about what the assignment is worth this term — clamp rather than trust the old total.
        earned = min(float(s["total_score"] or 0), points_possible)
        diagnostic = {k: v for k, v in
                      (("q2_effort", s["q2_effort"]), ("q3_understanding", s["q3_understanding"]))
                      if v is not None}
        cur.execute("""
            INSERT INTO app.grades (enrollment_id, assignment_offering_id, submission_id,
                                    points_earned, points_possible, question_scores,
                                    diagnostic, source, is_finalized)
            VALUES (%s,%s,%s,%s,%s,%s,%s,'ai_suggested',false)
            ON CONFLICT (enrollment_id, assignment_offering_id) DO UPDATE
              SET points_earned   = EXCLUDED.points_earned,
                  question_scores = EXCLUDED.question_scores,
                  diagnostic      = EXCLUDED.diagnostic,
                  submission_id   = EXCLUDED.submission_id""",
            (enr, offering_id, sub_id, earned, points_possible,
             json.dumps(s["question_scores"] or {}), json.dumps(diagnostic)))
        n_grade += 1

    print(f"  {n_sub:>5}  submissions (committed)")
    print(f"  {n_act:>5}  submission_activities (written answers)")
    print(f"  {n_grade:>5}  grades (ai_suggested, unfinalized)")
    if skipped:
        print(f"\n  {len(skipped)} response(s) skipped — student not enrolled in this offering:")
        print(f"    {', '.join(str(s) for s in skipped[:10])}"
              + (" …" if len(skipped) > 10 else ""))

    if args.commit:
        app_conn.commit()
        print("\nCOMMITTED.  Remove it again with:  --undo --commit")
    else:
        app_conn.rollback()
        print("\nRolled back — dry run. Re-run with --commit to apply.")

    cur.close()
    app_conn.close()


if __name__ == "__main__":
    main()
