#!/usr/bin/env python
"""Migrate `public` content and roster into schema `app` (PREP v2).

DRY RUN BY DEFAULT, per CORE.md: prints the full plan and writes nothing unless --commit
is passed. Idempotent — every insert is keyed on a natural key and re-running changes
nothing. The whole run is one transaction.

PREREQUISITE — the migration read window (app_schema_bootstrap.sql §8), run as `postgres`:

    GRANT USAGE ON SCHEMA public TO prep_app_owner;
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO prep_app_owner;

It is SELECT only: even while open, nothing here can write to, alter, or drop anything in
`public`. Close it again afterwards:

    REVOKE SELECT ON ALL TABLES IN SCHEMA public FROM prep_app_owner;
    REVOKE USAGE  ON SCHEMA public              FROM prep_app_owner;

=========================================================================================
DECISIONS ENCODED HERE  (agreed with Matthew, 2026-07-20)
=========================================================================================

WHAT IS DELIBERATELY LEFT BEHIND — all of it is test data, and none is real student work:
  * 64 responses + 64 unfinalized scores on preflight-02 — generated by
    scripts/training/seed_training_preflight02.py, not submitted by students
  * 6 rows in preflight_interaction_reports_backup_20260623 (June, pre-term)
  * 2 interaction_analysis rows scoped to section "M5A", which does not exist
  * assignments.analysis_report (1 row, from the training run)
  * the empty `extensions` and `lesson_completions` tables
The originals stay untouched in `public` if they are ever wanted.

AN INTERACTION MIGRATES IFF A LESSON CLAIMS IT. That single rule resolves the duplicate
lesson-02 slug the way Matthew chose: `lesson-02-electric-charge-coulombs-law` is referenced
by lesson-02 and comes across; `lesson-02-electric-charge-and-coulombs-law` is referenced by
nothing and is dropped, along with its analysis rows and backup reports.
  >>> The activity slug is the FROZEN CONTRACT surface. If a deployed artifact posts to the
  >>> other slug, this is the wrong call and must be revisited BEFORE students launch it.

SLUGS ARE DE-PREFIXED. phys-110 assignment ids were namespaced `phys-110-preflight-NN` in
July 2026 to dodge a global-PK collision. app.assignments scopes slug by course
(UNIQUE (course_id, slug)), so the prefix is redundant: both courses get plain
`preflight-NN`. The collision that forced the prefix cannot recur.

GRADING MODE IS 'points', NOT 'effort'. Written preflights are scored per question today.
LESSON-UNIFICATION.md D3 proposes moving to effort-gating on both paths, but that is a
pedagogical decision that has not been made real, and a migration is the wrong place to make
it silently. Switching later is one UPDATE per offering.

GRADED-VS-PRACTICE COMES FROM THE OLD completion_policy:
    policy 'preflight'  -> written graded, interactive present but practice
    policy 'choice'     -> both graded (the student picks)
    no lesson           -> written graded, nothing else
=========================================================================================
"""
import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "supabase" / "admin"))
from app_tier_check import load, connect  # noqa: E402

TERM = {
    "code": "fall-2026",
    "label": "Fall 2026",
    "starts_on": "2026-08-06",
    "ends_on": "2026-12-10",
    "finals_start": "2026-12-12",
    "finals_end": "2026-12-16",
    "grades_due_on": "2026-12-21",
}

counts = {}


def note(step, n):
    counts[step] = n
    print(f"  {n:>5}  {step}")


def parse_section_code(code):
    """'M1A' -> (['M'], 1). Falls back gracefully for anything unexpected."""
    m = re.match(r"^([MTWRF])(\d)", code or "")
    if not m:
        return [], None
    return [m.group(1)], int(m.group(2))


def position_from_slug(slug):
    m = re.search(r"(\d+)\s*$", slug or "")
    return int(m.group(1)) if m else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--commit", action="store_true",
                    help="actually write; otherwise the transaction is rolled back")
    args = ap.parse_args()

    cfg, tiers = load()
    conn = connect(cfg, tiers["owner"])
    conn.autocommit = False
    cur = conn.cursor()
    cur.execute("SET search_path = app, public")

    try:
        cur.execute("SELECT count(*) FROM public.courses")
    except Exception:
        conn.rollback()
        print("The migration read window is closed — cannot read `public`.\n")
        print("  Run as postgres in the SQL Editor, then re-run this script:\n")
        print("    GRANT USAGE ON SCHEMA public TO prep_app_owner;")
        print("    GRANT SELECT ON ALL TABLES IN SCHEMA public TO prep_app_owner;\n")
        sys.exit(2)

    print(f"{'DRY RUN — nothing will be written' if not args.commit else 'COMMITTING'}\n")
    print("Migrating:")

    # ---------------------------------------------------------------- term
    cur.execute("""INSERT INTO app.terms (code,label,starts_on,ends_on,finals_start,
                                          finals_end,grades_due_on)
                   VALUES (%(code)s,%(label)s,%(starts_on)s,%(ends_on)s,%(finals_start)s,
                           %(finals_end)s,%(grades_due_on)s)
                   ON CONFLICT (code) DO UPDATE SET label=EXCLUDED.label,
                     starts_on=EXCLUDED.starts_on, ends_on=EXCLUDED.ends_on,
                     finals_start=EXCLUDED.finals_start, finals_end=EXCLUDED.finals_end,
                     grades_due_on=EXCLUDED.grades_due_on
                   RETURNING id""", TERM)
    term_id = cur.fetchone()[0]
    note("term (fall-2026)", 1)

    # ---------------------------------------------------------------- courses + offerings
    cur.execute("SELECT id, title FROM public.courses ORDER BY id")
    course_id = {}      # 'phys-215' -> uuid
    offering_id = {}    # 'phys-215' -> uuid
    for code, title in cur.fetchall():
        cur.execute("""INSERT INTO app.courses (code,title) VALUES (%s,%s)
                       ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title
                       RETURNING id""", (code, title))
        course_id[code] = cur.fetchone()[0]
        cur.execute("""INSERT INTO app.course_offerings (course_id,term_id) VALUES (%s,%s)
                       ON CONFLICT (course_id,term_id) DO UPDATE SET is_active=true
                       RETURNING id""", (course_id[code], term_id))
        offering_id[code] = cur.fetchone()[0]
    note("courses", len(course_id))
    note("course_offerings", len(offering_id))

    # ---------------------------------------------------------------- sections
    cur.execute("SELECT id, course_id FROM public.sections ORDER BY id")
    section_id = {}     # 'M1A' -> uuid
    for code, ccode in cur.fetchall():
        days, period = parse_section_code(code)
        cur.execute("""INSERT INTO app.sections (course_offering_id,code,meeting_days,period)
                       VALUES (%s,%s,%s,%s)
                       ON CONFLICT (course_offering_id,code) DO UPDATE
                         SET meeting_days=EXCLUDED.meeting_days, period=EXCLUDED.period
                       RETURNING id""", (offering_id[ccode], code, days, period))
        section_id[code] = cur.fetchone()[0]
    note("sections", len(section_id))

    # ---------------------------------------------------------------- students + enrollments
    cur.execute("""SELECT student_id, name, section_id, auth_user_id
                     FROM public.students ORDER BY student_id""")
    roster = cur.fetchall()
    enrolled = 0
    for sid, name, sec, auth_uid in roster:
        cur.execute("""INSERT INTO app.students (student_id,name,auth_user_id) VALUES (%s,%s,%s)
                       ON CONFLICT (student_id) DO UPDATE
                         SET name=EXCLUDED.name, auth_user_id=EXCLUDED.auth_user_id""",
                    (sid, name, auth_uid))
        if sec and sec in section_id:
            cur.execute("""INSERT INTO app.enrollments (student_id,section_id,status)
                           VALUES (%s,%s,'active')
                           ON CONFLICT (student_id,section_id) DO NOTHING""",
                        (sid, section_id[sec]))
            enrolled += 1
    note("students", len(roster))
    note("enrollments", enrolled)

    # ---------------------------------------------------------------- staff
    cur.execute("SELECT id, name, is_global_admin FROM public.instructors")
    staff = cur.fetchall()
    for iid, name, admin in staff:
        cur.execute("""INSERT INTO app.instructors (id,name,is_global_admin) VALUES (%s,%s,%s)
                       ON CONFLICT (id) DO UPDATE
                         SET name=EXCLUDED.name, is_global_admin=EXCLUDED.is_global_admin""",
                    (iid, name, bool(admin)))
    note("instructors", len(staff))

    # instructor_course_access -> offering-wide staff rows
    cur.execute("SELECT instructor_id, course_id, role FROM public.instructor_course_access")
    sa = 0
    for iid, ccode, role in cur.fetchall():
        if ccode not in offering_id:
            continue
        cur.execute("""INSERT INTO app.staff_assignments
                         (instructor_id,course_offering_id,section_id,role)
                       VALUES (%s,%s,NULL,%s)
                       ON CONFLICT (instructor_id,course_offering_id,section_id) DO UPDATE
                         SET role=EXCLUDED.role""", (iid, offering_id[ccode], role))
        sa += 1
    # sections.instructor_id -> section-scoped staff rows
    cur.execute("""SELECT s.instructor_id, s.course_id, s.id FROM public.sections s
                    WHERE s.instructor_id IS NOT NULL""")
    for iid, ccode, sec in cur.fetchall():
        cur.execute("""INSERT INTO app.staff_assignments
                         (instructor_id,course_offering_id,section_id,role)
                       VALUES (%s,%s,%s,'instructor')
                       ON CONFLICT (instructor_id,course_offering_id,section_id) DO NOTHING""",
                    (iid, offering_id[ccode], section_id[sec]))
        sa += 1
    note("staff_assignments", sa)

    # ---------------------------------------------------------------- lesson metadata
    # The old `lessons` table collapses INTO app.assignments: a lesson was already the
    # container joining a preflight to an interaction. Index it by preflight_id.
    cur.execute("""SELECT preflight_id, interaction_id, completion_policy, objectives,
                          lesson_number, title, is_published
                     FROM public.lessons WHERE preflight_id IS NOT NULL""")
    lesson_by_preflight = {r[0]: r for r in cur.fetchall()}
    # An interaction migrates iff a lesson claims it.
    claimed_interactions = {r[1] for r in lesson_by_preflight.values() if r[1]}

    # ---------------------------------------------------------------- assignments + activities
    cur.execute("""SELECT id, course_id, title, description, questions, due_date_m, due_date_t,
                          is_published, reading_link, reference_pdf, reference_pages
                     FROM public.assignments ORDER BY course_id, id""")
    rows = cur.fetchall()
    n_written = n_ao = n_oa = n_due = 0
    ao_by_assignment = {}

    for (aid, ccode, title, desc, questions, dm, dt, pub, link, pdf, pages) in rows:
        slug = aid[len(ccode) + 1:] if aid.startswith(ccode + "-") else aid
        lesson = lesson_by_preflight.get(aid)
        objectives = lesson[3] if lesson else []

        cur.execute("""INSERT INTO app.assignments (course_id,kind_id,slug,title,description,objectives)
                       VALUES (%s,'preflight',%s,%s,%s,%s)
                       ON CONFLICT (course_id,slug) DO UPDATE
                         SET title=EXCLUDED.title, description=EXCLUDED.description,
                             objectives=EXCLUDED.objectives
                       RETURNING id""",
                    (course_id[ccode], slug, title, desc, objectives))
        asg = cur.fetchone()[0]

        w_content = {"questions": questions, "reading_link": link,
                     "reference_pdf": pdf, "reference_pages": pages}
        w_slug = f"{ccode}-{slug}-written"
        cur.execute("""INSERT INTO app.activities (assignment_id,modality,slug,title,content)
                       VALUES (%s,'written',%s,%s,%s)
                       ON CONFLICT (assignment_id,modality) DO UPDATE
                         SET content=EXCLUDED.content
                       RETURNING id""",
                    (asg, w_slug, title, __import__("json").dumps(w_content)))
        written_act = cur.fetchone()[0]
        n_written += 1

        interactive_act = None
        if lesson and lesson[1] and lesson[1] in claimed_interactions:
            cur.execute("""SELECT id, title, description, artifact_url
                             FROM public.interactions WHERE id=%s""", (lesson[1],))
            it = cur.fetchone()
            if it:
                cur.execute("""INSERT INTO app.activities (assignment_id,modality,slug,title,content)
                               VALUES (%s,'interactive',%s,%s,%s)
                               ON CONFLICT (assignment_id,modality) DO UPDATE
                                 SET content=EXCLUDED.content
                               RETURNING id""",
                            (asg, it[0], it[1],
                             __import__("json").dumps({"artifact_url": it[3],
                                                       "description": it[2]})))
                interactive_act = cur.fetchone()[0]

        total_points = sum((q.get("points") or 0) for q in (questions or [])) or 2
        cur.execute("""INSERT INTO app.assignment_offerings
                         (course_offering_id,assignment_id,points_possible,grading_mode,
                          switch_policy,due_at,is_published,position)
                       VALUES (%s,%s,%s,'points','lock_on_commit',%s,%s,%s)
                       ON CONFLICT (course_offering_id,assignment_id) DO UPDATE
                         SET points_possible=EXCLUDED.points_possible,
                             due_at=EXCLUDED.due_at, is_published=EXCLUDED.is_published,
                             position=EXCLUDED.position
                       RETURNING id""",
                    (offering_id[ccode], asg, total_points, dm, pub, position_from_slug(slug)))
        ao = cur.fetchone()[0]
        ao_by_assignment[aid] = ao
        n_ao += 1

        policy = lesson[2] if lesson else "preflight"
        w_role = "graded"
        i_role = "graded" if policy == "choice" else "practice"

        cur.execute("""INSERT INTO app.offering_activities
                         (assignment_offering_id,activity_id,grading_role,position)
                       VALUES (%s,%s,%s,0)
                       ON CONFLICT (assignment_offering_id,activity_id) DO UPDATE
                         SET grading_role=EXCLUDED.grading_role""", (ao, written_act, w_role))
        n_oa += 1
        if interactive_act:
            cur.execute("""INSERT INTO app.offering_activities
                             (assignment_offering_id,activity_id,grading_role,position)
                           VALUES (%s,%s,%s,1)
                           ON CONFLICT (assignment_offering_id,activity_id) DO UPDATE
                             SET grading_role=EXCLUDED.grading_role""",
                        (ao, interactive_act, i_role))
            n_oa += 1

        # Per-section deadlines: M-day sections take due_date_m, T-day sections due_date_t.
        for code, sid in section_id.items():
            cur.execute("SELECT course_offering_id FROM app.sections WHERE id=%s", (sid,))
            if cur.fetchone()[0] != offering_id[ccode]:
                continue
            due = dm if code.startswith("M") else dt
            if due is None:
                continue
            cur.execute("""INSERT INTO app.assignment_due_dates
                             (assignment_offering_id,section_id,due_at) VALUES (%s,%s,%s)
                           ON CONFLICT (assignment_offering_id,section_id) DO UPDATE
                             SET due_at=EXCLUDED.due_at""", (ao, sid, due))
            n_due += 1

    note("assignments (containers)", len(rows))
    note("activities: written", n_written)
    note("activities: interactive", len(claimed_interactions))
    note("assignment_offerings", n_ao)
    note("offering_activities", n_oa)
    note("assignment_due_dates", n_due)

    # ---------------------------------------------------------------- report what was skipped
    print("\nDeliberately NOT migrated (test data — originals remain in `public`):")
    cur.execute("SELECT count(*) FROM public.responses")
    print(f"  {cur.fetchone()[0]:>5}  responses (seed_training_preflight02.py)")
    cur.execute("SELECT count(*) FROM public.scores")
    print(f"  {cur.fetchone()[0]:>5}  scores (0 finalized)")
    cur.execute("SELECT count(*) FROM public.preflight_interaction_reports_backup_20260623")
    print(f"  {cur.fetchone()[0]:>5}  backup interaction reports (June, pre-term)")
    cur.execute("SELECT count(*) FROM public.interaction_analysis WHERE section_id='M5A'")
    print(f"  {cur.fetchone()[0]:>5}  interaction_analysis rows for section M5A (no such section)")
    cur.execute("""SELECT count(*) FROM public.interactions i
                    WHERE NOT EXISTS (SELECT 1 FROM public.lessons l WHERE l.interaction_id=i.id)""")
    print(f"  {cur.fetchone()[0]:>5}  interactions claimed by no lesson (incl. the lesson-02 duplicate)")

    if args.commit:
        conn.commit()
        print("\nCOMMITTED.")
    else:
        conn.rollback()
        print("\nRolled back — dry run. Re-run with --commit to apply.")

    cur.close()
    conn.close()


if __name__ == "__main__":
    main()
